In [1]:
import cv2
import numpy as np

#lay file nhan dien mat
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_alt.xml")

#lay webcam
cap = cv2.VideoCapture(0)

while(True):
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #doi mau
    faces = face_cascade.detectMultiScale(gray) #lay khuon mat
    print(faces)
    for(x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,0), 2)
        cv2.imshow('DETECTING FACE', frame)
    
    #dieu kien de thoat vong true
    if(cv2.waitKey(1) & 0xFF == ord('q')):
        break
    
cap.release() #giai phong bo nho
cv2.destroyAllWindows() #tat ct'''    

[[282 175 239 239]]
[[285 184 226 226]]
[[287 184 225 225]]
[[288 185 224 224]]
[[283 179 236 236]]
[[283 176 237 237]]
[[288 180 230 230]]
[[289 184 227 227]]
[[289 180 230 230]]
[[288 181 231 231]]
[[288 184 227 227]]
[[282 184 233 233]]
[[285 190 224 224]]
[[278 189 228 228]]
[[278 188 226 226]]
[[281 191 219 219]]
[[277 187 222 222]]
[[274 190 220 220]]
[[270 188 226 226]]
[[267 187 231 231]]
[[264 184 235 235]]
[[260 183 236 236]]
[[259 183 233 233]]
[[260 185 230 230]]
[[260 187 226 226]]
[[259 185 233 233]]
[[262 188 224 224]]
[[264 188 227 227]]
[[264 185 228 228]]
[[263 185 235 235]]
[[268 185 230 230]]
[[268 182 239 239]]
[[277 186 230 230]]
[[281 186 228 228]]
[[285 188 226 226]]
[[284 182 235 235]]
[[286 187 229 229]]
[[286 185 233 233]]
[[286 192 221 221]]
[[289 201 212 212]]
[[280 202 220 220]]
[[275 203 228 228]]
[[277 209 230 230]]
[[284 209 229 229]]
[[284 206 238 238]]
[[292 193 240 240]]
[[290 164 264 264]]
[[302 139 270 270]]
[[315 115 280 280]]
[[361 106 252 252]]
