In [1]:
import cv2
import numpy as np
import os
from PIL import Image

#cv2.face la thu vien de training hinh anh
recognizer = cv2.face.LBPHFaceRecognizer_create()

path = 'dataSet'

def getImageWithId(path):
    imagePaths = [os.path.join(path, f) for f in os.listdir(path)] #truy cap vao tat ca duong dan anh 
    
    #print(imagePaths)
    
    faces = []
    IDs = []
    
    for imagePath in imagePaths:
        faceImg = Image.open(imagePath).convert('L') #L la grayscale, convert thang PIL image
        
        faceNp = np.array(faceImg, 'uint8') #chuyen anh thanh dang array de train (cac ma tran diem anh?)
        
        print(faceNp)

        #cat va lay theo ptu
        Id = int(imagePath.split('\\')[1].split('.')[1]) 
        
        faces.append(faceNp)
        IDs.append(Id)
        
        cv2.imshow('Training',faceNp)
        cv2.waitKey(10)
   
    return faces, IDs


faces, Ids = getImageWithId(path)

#train models
recognizer.train(faces, np.array(Ids))

if not os.path.exists('recognizer'): #neu ma chua co
    os.makedirs('recognizer')

recognizer.save('recognizer/trainingData.yml')

cv2.destroyAllWindows()
    

[[ 39  38  39 ...  94  98  98]
 [ 37  35  36 ...  94  99 102]
 [ 42  37  38 ...  96  98 102]
 ...
 [157 157 157 ... 146 147 146]
 [159 158 157 ... 144 147 147]
 [161 161 160 ... 142 145 145]]
[[ 34  36  35 ...  91  91  85]
 [ 33  33  32 ...  91  92  90]
 [ 34  32  31 ...  92  92  94]
 ...
 [161 160 161 ... 149 148 148]
 [161 160 160 ... 150 149 149]
 [162 162 159 ... 152 150 150]]
[[ 44  42  35 ...  73  72  76]
 [ 43  39  33 ...  73  72  75]
 [ 45  38  34 ...  77  75  76]
 ...
 [142 141 142 ... 141 142 142]
 [144 144 143 ... 139 142 141]
 [146 146 145 ... 141 144 143]]
[[ 62  59  55 ...  60  59  62]
 [ 64  64  60 ...  58  59  64]
 [ 66  68  64 ...  61  60  61]
 ...
 [139 138 139 ... 142 138 141]
 [142 139 138 ... 140 136 142]
 [139 138 138 ... 139 136 141]]
[[ 61  59  60 ...  84  73  69]
 [ 62  57  56 ...  85  80  79]
 [ 63  60  57 ...  91  83  83]
 ...
 [145 143 145 ... 140 143 146]
 [146 142 143 ... 139 143 145]
 [146 142 143 ... 144 146 146]]
[[ 63  62  58 ...  61  53  56]
 [ 63  62

[[ 69  70  64 ...  80  76  75]
 [ 72  73  64 ...  78  77  75]
 [ 71  69  60 ...  74  79  78]
 ...
 [160 156 155 ... 154 156 157]
 [160 156 155 ... 153 156 158]
 [158 155 155 ... 154 157 158]]
[[ 32  34  43 ...  86  90 101]
 [ 36  33  34 ...  88  86  91]
 [ 52  49  41 ...  85  87  89]
 ...
 [156 157 159 ... 167 168 166]
 [158 156 158 ... 165 166 161]
 [160 157 159 ... 162 163 158]]
[[ 73  66  64 ... 255 252 254]
 [ 64  61  62 ... 250 255 252]
 [ 61  57  52 ... 255 254 255]
 ...
 [157 158 155 ... 147 146 146]
 [156 157 154 ... 149 148 149]
 [155 156 154 ... 149 149 149]]
[[ 48  45  38 ... 252 255 255]
 [ 41  43  41 ... 255 254 255]
 [ 38  41  42 ... 252 255 255]
 ...
 [157 159 158 ... 153 152 158]
 [159 157 154 ... 153 151 153]
 [157 156 153 ... 152 151 151]]
[[ 38  38  37 ... 255 255 255]
 [ 39  37  35 ... 255 255 255]
 [ 39  38  36 ... 255 255 255]
 ...
 [156 152 155 ... 162 164 165]
 [157 153 154 ... 161 163 164]
 [157 153 153 ... 156 158 160]]
[[ 32  33  29 ... 255 255 255]
 [ 27  30

[[ 29  27  24 ...  88  90  74]
 [ 25  27  26 ...  87  87  79]
 [ 28  32  31 ...  85  85  83]
 ...
 [156 156 156 ... 150 148 150]
 [152 158 160 ... 155 154 152]
 [157 156 158 ... 155 156 154]]
[[ 57  57  54 ...  62  59  58]
 [ 60  60  58 ...  66  63  61]
 [ 59  57  55 ...  66  62  60]
 ...
 [154 154 155 ... 187 186 184]
 [155 153 153 ... 186 185 185]
 [154 153 154 ... 182 181 181]]
[[ 49  51  44 ...  64  61  62]
 [ 48  49  46 ...  63  62  62]
 [ 51  50  51 ...  63  62  59]
 ...
 [162 159 158 ... 161 161 160]
 [157 156 156 ... 160 158 157]
 [155 154 157 ... 155 156 160]]
[[ 57  54  50 ...  68  69  71]
 [ 56  57  55 ...  68  68  70]
 [ 56  55  53 ...  68  70  70]
 ...
 [164 164 165 ... 163 164 163]
 [162 162 162 ... 164 165 164]
 [160 161 161 ... 162 163 164]]
[[ 65  67  72 ... 192 216 248]
 [ 76  74  76 ... 198 190 214]
 [ 80  78  76 ... 191 175 196]
 ...
 [165 161 162 ... 179 180 182]
 [160 159 161 ... 173 176 178]
 [159 158 160 ... 172 175 176]]
[[ 49  39  39 ... 191 231 254]
 [ 47  42

[[ 42  42  35 ... 225 249 253]
 [ 38  37  31 ... 252 250 253]
 [ 39  37  32 ... 251 252 254]
 ...
 [155 151 147 ... 147 146 143]
 [152 152 150 ... 147 147 145]
 [152 152 151 ... 146 148 147]]
[[ 40  40  42 ... 206 216 229]
 [ 38  40  41 ... 238 233 232]
 [ 37  39  41 ... 253 252 245]
 ...
 [154 156 154 ... 144 146 147]
 [156 152 150 ... 142 145 145]
 [154 150 148 ... 142 140 140]]
[[ 35  36  32 ... 197 210 193]
 [ 35  38  35 ... 212 230 228]
 [ 31  36  35 ... 202 237 249]
 ...
 [148 146 144 ... 143 146 148]
 [150 148 149 ... 143 146 152]
 [152 150 151 ... 140 144 150]]
[[ 42  41  39 ... 254 254 254]
 [ 41  41  41 ... 254 254 254]
 [ 36  39  42 ... 254 254 254]
 ...
 [154 152 153 ... 143 143 142]
 [153 152 154 ... 142 142 141]
 [151 153 155 ... 142 141 141]]
[[ 46  41  38 ... 253 254 254]
 [ 42  39  37 ... 255 254 254]
 [ 39  38  36 ... 255 254 254]
 ...
 [155 152 151 ... 141 143 145]
 [154 154 155 ... 146 144 141]
 [154 154 155 ... 144 139 136]]
[[ 32  33  32 ... 231 251 255]
 [ 35  34

[[ 25  28  29 ... 255 255 255]
 [ 28  30  30 ... 255 255 255]
 [ 34  35  34 ... 255 255 255]
 ...
 [146 145 143 ... 164 165 165]
 [143 143 142 ... 164 165 165]
 [141 142 142 ... 162 163 162]]
[[ 35  31  30 ... 255 255 255]
 [ 34  32  31 ... 255 255 255]
 [ 33  35  32 ... 255 255 255]
 ...
 [126 126 127 ... 158 158 158]
 [123 124 125 ... 160 160 158]
 [122 121 122 ... 154 151 146]]
[[ 30  25  24 ... 255 255 255]
 [ 29  26  27 ... 255 255 255]
 [ 29  27  28 ... 255 255 255]
 ...
 [139 135 135 ... 143 143 142]
 [141 138 136 ... 143 142 140]
 [141 141 139 ... 141 140 138]]
[[ 28  31  33 ... 255 255 255]
 [ 25  27  30 ... 255 255 255]
 [ 23  24  26 ... 255 255 255]
 ...
 [144 143 142 ... 136 137 137]
 [142 144 144 ... 136 138 139]
 [146 148 148 ... 138 142 144]]
[[ 29  31  26 ... 109 120 143]
 [ 27  28  25 ... 117 136 178]
 [ 26  25  25 ... 133 172 222]
 ...
 [154 152 150 ... 136 135 136]
 [156 154 151 ... 137 135 135]
 [156 154 152 ... 138 134 132]]
[[ 31  28  30 ... 110 110 110]
 [ 33  29